version: '3.3'
services:
  word-replacer:
    image: wichen1214/word-replacer
    container_name: word-replacer
    restart: always
    ports:
      - "8080:8080"
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DDL_AUTO=update
    #validate: validate the schema, makes no changes to the database.
    #update: update the schema.
    #create: creates the schema, destroying previous data.
    #create-drop: drop the schema at the end of the session
    #none: is all other cases.
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: zona-admin
      POSTGRES_PASSWORD: zonazona-admin
      POSTGRES_DB: DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data: