version: '3.3'
services:
  word-replacer:
    image: wichen1214/word-replacer
    container_name: word-replacer
    restart: always
    ports:
      - "8080:8080"
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: zona-admin
      POSTGRES_PASSWORD: zonazona-admin
      POSTGRES_DB: DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data: